# Generated by Django 2.1.5 on 2019-02-03 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('dateposted', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobprofile', models.CharField(max_length=80)),
                ('jobplace', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=30)),
                ('jobdescription', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
