# Generated by Django 2.2.4 on 2020-11-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20201126_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applyHere',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
